import os
import json
from dotenv import load_dotenv
import google.generativeai as genai
from app.export.pptx_generator import generate_pptx_file

load_dotenv()
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))


def generate_slide_content(company, contexts, aiNews, companyInsight, slideCount):
    """
    Generate structured slide content using Gemini API.
    Returns list of dicts: [{"title": ..., "content": [...]}, ...]
    """

    # 🔥 Prompt lebih terstruktur
    prompt = f"""
Create a presentation about **{company}** in English.

Context: {contexts}
Include AI News: {aiNews}
Include Company Insight: {companyInsight}

The presentation must have exactly {slideCount} slides with the following structure:

1. Title Slide → title of the presentation + 3 subtitle items (company name, topic).
2. Introduction → 3 points: background, main issues, objectives.
3. Main Topic(s) → at least 3 bullet points per slide.
4. Conclusion → 3 points: summary, benefits, next actions.

Rules:
- Always return valid JSON array.
- Each item must have: "title" (string) and "content" (list of 3+ strings).
- Do NOT include explanations outside JSON.
- Ensure there are exactly {slideCount} items.
Format example:
[
  {{"title": "Company Presentation", "content": ["Subtitle 1", "Subtitle 2", "Subtitle 3"]}},
  {{"title": "Introduction", "content": ["Point 1", "Point 2", "Point 3"]}},
  ...
]
"""

    try:
        model = genai.GenerativeModel("gemini-2.0-flash")
        response = model.generate_content(prompt)
        raw_text = response.text.strip()

        # Bersihkan jika ada blok code
        if raw_text.startswith("```"):
            raw_text = raw_text.strip("`").replace("json", "").strip()

        slides_content = json.loads(raw_text)

        # Normalisasi isi content
        for slide in slides_content:
            slide["content"] = [
                "".join(c).strip() if isinstance(c, list) else str(c).strip()
                for c in slide.get("content", [])
            ]
            # pastikan minimal 3 poin
            while len(slide["content"]) < 3:
                slide["content"].append("Additional point.")

        # Validasi jumlah slide
        if len(slides_content) != slideCount:
            raise ValueError("Slide count mismatch from Gemini")

        return slides_content

    except Exception as e:
        print("⚠️ Gemini failed, using fallback:", e)

        # 🔥 Fallback dengan struktur fix
        slides_content = [
            {
                "title": f"{company} Presentation",
                "content": [f"{company}", "Generated by AI", "2025"]
            },
            {
                "title": "Introduction",
                "content": ["Background of the company.", "Main issues.", "Objectives."]
            }
        ]

        # Tambahkan topik sesuai jumlah slide
        for i in range(slideCount - 3):
            slides_content.append({
                "title": f"Main Topic {i+1}",
                "content": [f"Point {i+1}.1", f"Point {i+1}.2", f"Point {i+1}.3"]
            })

        slides_content.append({
            "title": "Conclusion",
            "content": ["Summary.", "Benefits.", "Next actions."]
        })

        return slides_content


def create_ppt(slides_content, filepath, template="general", branding="default"):
    """
    Wrapper function to generate PPTX file.
    """
    generate_pptx_file(
        slides_content,
        filepath,
        template=template,
        branding=branding
    )
